### ISSUE TITLE
Incorrect path to RSS icon on test page

### ISSUE THREAD

**Issue by bondjimbond** [mjordan/islandora_onthisday#11]
/onthisday provides an RSS icon, using the path `/sites/all/modules/islandora_solr_search/islandora_solr_config/images/rss.png`.

The test pages (i.e. /onthisday/[mm-dd]) incorrectly add /onthisday to the RSS icon path:
`/onthisday/sites/all/modules/islandora_solr_search/islandora_solr_config/images/rss.png`

Not a big deal if using for testing, but the test pages would also work well as "look up a date" pages.

**Comment by bondjimbond** [comment]
@mjordan Weirdly, I tried printing the $rss_icon_path variable to see what you get, and it shows the same on both the proper gallery page and when you're looking at the test/specific date page. Needs further digging.

**Comment by mjordan** [comment]
Oops, I didn't see this last comment before merging. Did you figure that out?

**Comment by bondjimbond** [comment]
That comment was before I tried writing a fix. Merge should be good. :)
