### ISSUE TITLE
Ignore Newspaper Page objects

### ISSUE THREAD

**Issue by bondjimbond** [mjordan/islandora_onthisday#13]
If you have a newspaper issue with multiple pages on a given day, onthisday will list each page from that issue (i.e. June 30, 1923 page 1, June 30, 1923 page 2, etc.)... Should just display the Issue, not the individual page.

Don't know whether this happens with Books.

**Comment by mjordan** [comment]
We already have a "Collections to exclude" admin setting. What if we added a "Content models to exclude" setting, where we could specify newspaper and book pages?

**Comment by bondjimbond** [comment]
That would be perfect.

**Comment by bondjimbond** [comment]
Bumping this. I was thinking of doing some work on the issue basing it off your "collections to exclude" setting, but I don't actually see that setting in the module. Is that on an unmerged commit?

**Comment by mjordan** [comment]
Nope, the admin setting for it is at https://github.com/mjordan/islandora_onthisday/blob/7.x/islandora_onthisday.module#L85.

**Comment by bondjimbond** [comment]
Aaaah, didn't realize it was hidden by the checkbox. Thanks.

I'll see if I can do anything with this when I have a minute.

**Comment by mjordan** [comment]
@bondjimbond great, thank you.

**Comment by mjordan** [comment]
Closed with bf2c9b0fc21108de141115d607fa756ebef56dba.
