### ISSUE TITLE
Respect namespace restrictions

### ISSUE THREAD

**Issue by bondjimbond** [mjordan/islandora_onthisday#17]
Onthisday displays objects from the whole repository, and ignores any namespace restrictions that might be set up in admin/islandora/configure. On a restricted site, this means that links to objects will be generated, leading to a 403 error when user clicks on them.

**Comment by mjordan** [comment]
Thanks for noticing - that's a pretty obvious omission. I'll see if I can find time to fix that.

**Comment by bondjimbond** [comment]
@mjordan I opened PR #18 ... seems to work, but if you'd like to test, I'd appreciate it

**Comment by mjordan** [comment]
Fixed with 36cc2a8a1f171b3d10da4ac6dca4e43fbd004dc1.
