### ISSUE TITLE
Block title - move 'More' link

### ISSUE THREAD

**Issue by librarychik** [mjordan/islandora_onthisday#7]
Can the 'More' link appended to the block title be moved to a new line? Possibly after the object title?  Currently it is very large and possibly confusing attached to the block title.  

See below:

![otdmore](https://cloud.githubusercontent.com/assets/877577/18286050/ea8b457c-7425-11e6-9376-b6ebe7b35a03.png)

**Comment by mjordan** [comment]
What if the option to show the object's collection is on, like in this example:

![onthisday_issue_7](https://cloud.githubusercontent.com/assets/403918/18286560/3806187a-7428-11e6-9706-230d83a2e2c1.png)

Should the 'More...' link go below that?

**Comment by mjordan** [comment]
Also, we probably should provide an admin option to show the 'More...' link or not - what do you think?

**Comment by librarychik** [comment]
I like the more link at the end (of title or collection) of last line of the object.  What do you think of See more instead of just more?  (or View more). 

I wonder if we need the collection at all? Once you navigate to the object you can see the collection in the breadcrumbs and also below the object.

 Yes, I agree, the admin option is a good idea.

**Comment by mjordan** [comment]
Showing the collection(s) is currently an option in the On This Day admin options. We can turn it off. I like 'See more', thanks for the suggestion.

**Comment by mjordan** [comment]
As an addendum to this issue, we should provide a separate config option for the block and the gallery for showing collection links.

**Comment by mjordan** [comment]
Closed with 8a33f55901d961d7ebdd44a7226a50a81cb45a13.
